/**
 * Extracts just the Phosphor glyphs this app uses into a small React module,
 * so the build doesn't ship the full multi-megabyte icon font.
 *
 *   node scripts/build-icons.mjs
 *
 * Phosphor is MIT licensed (https://github.com/phosphor-icons/web).
 */
import { readFileSync, writeFileSync } from 'node:fs'

const WANTED = {
  regular: ['upload-simple', 'download-simple', 'trash', 'x'],
  bold: ['plus', 'cursor-click', 'caret-left', 'caret-right', 'calendar-blank', 'squares-four', 'check'],
  fill: ['users-three', 'warning-circle', 'calendar-dots'],
}

const entries = []
for (const [weight, names] of Object.entries(WANTED)) {
  const selection = JSON.parse(
    readFileSync(`node_modules/@phosphor-icons/web/src/${weight}/selection.json`, 'utf8'),
  )
  for (const name of names) {
    // Non-regular sets suffix the weight, and a glyph may carry several
    // comma-separated aliases.
    const target = weight === 'regular' ? name : `${name}-${weight}`
    const icon = selection.icons.find((candidate) =>
      candidate.properties.name.split(',').some((alias) => alias.trim() === target),
    )
    if (!icon) throw new Error(`No "${target}" glyph in the ${weight} set`)
    entries.push([`${weight}/${name}`, icon.icon.paths.join(' ')])
  }
}

const body = entries
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([key, path]) => `  '${key}':\n    '${path}',`)
  .join('\n')

writeFileSync(
  'src/components/icon-paths.ts',
  `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Phosphor Icons (MIT) glyph outlines, in the icon set's native 1024 grid.
export const ICON_PATHS: Record<string, string> = {
${body}
}
`,
)

console.log(`Wrote ${entries.length} icon paths.`)
